basePath: /api/v1
definitions:
  GetResourceByUid:
    properties:
      uid:
        type: integer
    required:
    - uid
    type: object
  LoginByPhoneRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  SignupUsingPhoneRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  UpdateUserBroseRequest:
    properties:
      resource_id:
        type: integer
      uid:
        type: integer
    required:
    - resource_id
    - uid
    type: object
  UpdateUserClickRequest:
    properties:
      resource_id:
        type: integer
      uid:
        type: integer
    required:
    - resource_id
    - uid
    type: object
  UpdateUserLikeRequest:
    properties:
      resource_id:
        type: integer
      uid:
        type: integer
    required:
    - resource_id
    - uid
    type: object
  UpdateUserRequest:
    properties:
      email:
        type: string
      newpassword:
        type: string
      password:
        type: string
    type: object
  UpdateUserSaveRequest:
    properties:
      resource_id:
        type: integer
      uid:
        type: integer
    required:
    - resource_id
    - uid
    type: object
host: localhost:8083
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /action/browse:
    post:
      consumes:
      - application/json
      description: 更新用户的浏览记录
      parameters:
      - description: Uid--用户ID
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/UpdateUserBroseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: UpdateUserBrowse
      tags:
      - recommend
  /action/click:
    post:
      consumes:
      - application/json
      description: 更新用户点击记录
      parameters:
      - description: Uid--用户ID
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/UpdateUserClickRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: GetResourceByClick
      tags:
      - recommend
  /action/collect:
    post:
      consumes:
      - application/json
      description: 更新用户的点赞记录
      parameters:
      - description: Uid--用户ID
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/UpdateUserClickRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: GetResourceByCollect
      tags:
      - recommend
  /action/like:
    post:
      consumes:
      - application/json
      description: 更新用户点赞记录
      parameters:
      - description: Uid--用户ID
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/UpdateUserLikeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: GetResourceByLike
      tags:
      - recommend
  /action/save:
    post:
      consumes:
      - application/json
      description: 更新用户分享记录
      parameters:
      - description: Uid--用户ID
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/UpdateUserSaveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: GetResourceBySave
      tags:
      - recommend
  /action/search:
    post:
      consumes:
      - application/json
      description: 更新用户点赞记录
      parameters:
      - description: Uid--用户ID
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/UpdateUserLikeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: UpdateUserSearch
      tags:
      - recommend
  /login/common:
    post:
      consumes:
      - application/json
      description: 用户通过邮箱和密码登陆
      parameters:
      - description: Email--邮箱 和Password--密码
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/LoginByPhoneRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Response'
      summary: Login By Email
      tags:
      - login
  /login/user:
    post:
      consumes:
      - application/json
      description: 更新密码
      parameters:
      - description: Email--邮箱 和Password--密码 NewPassword-新密码
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Response'
      summary: UpdateUser
      tags:
      - login
  /recommend/browse:
    post:
      consumes:
      - application/json
      description: 通过用户的浏览记录推荐
      parameters:
      - description: Uid--用户ID
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/GetResourceByUid'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: GetResourceByBrowse
      tags:
      - recommend
  /recommend/click:
    post:
      consumes:
      - application/json
      description: 通过用户点击记录推荐
      parameters:
      - description: Uid--用户ID
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/GetResourceByUid'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: GetResourceByClick
      tags:
      - recommend
  /recommend/collect:
    post:
      consumes:
      - application/json
      description: 通过用户的收藏记录推荐
      parameters:
      - description: Uid--用户ID
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/GetResourceByUid'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: GetResourceByCollect
      tags:
      - recommend
  /recommend/like:
    post:
      consumes:
      - application/json
      description: 通过用户点击喜欢推荐
      parameters:
      - description: Uid--用户ID
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/GetResourceByUid'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: GetResourceByLike
      tags:
      - recommend
  /recommend/save:
    post:
      consumes:
      - application/json
      description: 通过用户的保存记录推荐
      parameters:
      - description: Uid--用户ID
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/GetResourceByUid'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: GetResourceBySave
      tags:
      - recommend
  /sign/common:
    post:
      consumes:
      - application/json
      description: 使用手机号和密码注册帐号
      parameters:
      - description: Phone--电话号码||Password-- 密码|| Name--昵称
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/SignupUsingPhoneRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: Sign up Using Phone
      tags:
      - sign
swagger: "2.0"
